### Filtering Data

In [3]:
import pandas as pd

In [4]:
df = pd.read_excel("1.Instructors_Tutorial\data\olympics-data.xlsx")

In [5]:
df.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [12]:
# Conditions can be applied it is just like masking numpy
df[df["weight_kg"]>170]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
59204,59630,Marek Galiński,1951-05-13,Wrocław,Dolnośląskie,POL,Poland,200.0,190.0,1999-09-28
60344,60777,Chris Taylor,1950-06-13,Dowagiac,Michigan,USA,United States,196.0,182.0,1979-06-30
91712,92442,Valentyn Rusliakov,1972-02-03,NaN,NaN,NaN,Ukraine,187.0,180.0,NaN
105671,106726,Dmitry Nosov,1980-04-09,Chita,Zabaykalsky Kray,RUS,Russian Federation,176.0,175.0,NaN
105715,106771,Aythami Ruano,1977-06-18,Las Palmas de Gran Canaria,Las Palmas,ESP,Spain,200.0,198.0,NaN
105722,106778,Leonel Wilfredo Ruiz,1975-07-27,NaN,NaN,NaN,Venezuela,187.0,178.0,NaN

In [7]:
# Multiple conditions can be applied by using ( ) & ( ) - like this
df[(df["height_cm"] == 150) & (df["weight_kg"]>50)].head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
769,773,Marcos Núñez,1961-01-07,NaN,NaN,NaN,Chile,150.0,72.0,NaN
777,781,Deng Yaping,1973-02-06,Zhengzhou,Henan,CHN,People's Republic of China,150.0,53.0,NaN
4414,4429,Teboho Mathibeli,1970-12-02,NaN,NaN,NaN,Lesotho,150.0,51.0,NaN
4783,4801,Christopher Ossai,1957-04-01,NaN,NaN,NaN,Nigeria,150.0,60.0,NaN
7493,7534,Jo Horny,1938-09-03,Bruxelles (Brussels),Région de Bruxelles-Capitale,BEL,Belgium,150.0,51.0,NaN

In [8]:
# By Using .loc you can make this simpler
df.loc[(df["height_cm"]>214) & (df["born_country"] == "USA")  , ["name" , "height_cm"]].head()

                    name  height_cm
5781      Tommy Burleson      223.0
6722    Shaquille O'Neal      216.0
6937      David Robinson      216.0
123850    Tyson Chandler      216.0

In [9]:
df.loc[df["name"].str.contains("Abhi")]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
92335,93075,Abhinav Bindra,1982-09-28,Dehradun,Uttar Pradesh,IND,India,173.0,70.0,NaN
104825,105851,Abhinn Shyam Gupta,1979-10-22,Allahabad,Uttar Pradesh,IND,India,172.0,68.0,NaN
140280,143784,Abhishek Verma,1989-08-01,Rohtak,Haryana,IND,India,NaN,NaN,NaN

In [17]:
df.loc[df["name"].str.contains("Keith|Abhi", case = False)].head()
# case False means that keith Keith KEITH all are same

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
1897,1907,Keith Hanlon,1966-09-01,NaN,NaN,NaN,Ireland,NaN,NaN,NaN
3505,3517,Keith Wallace,1961-03-29,Preston,England,GBR,Great Britain,165.0,51.0,1999-12-31
6228,6255,Keith Hartley,1940-10-15,Vancouver,British Columbia,CAN,Canada,200.0,85.0,NaN
8898,8946,Keith Mwila,1966-01-01,NaN,NaN,NaN,Zambia,NaN,NaN,1993-01-09
12053,12118,Keith Hervey,1898-11-03,Fulham,England,GBR,Great Britain,NaN,NaN,1973-02-22

In [16]:
df.loc[(df["born_country"].isin(["USA","CAN","GBR"])) & (df["name"].str.startswith("Keith")), ["name"]].head()

                 name
3505    Keith Wallace
6228    Keith Hartley
12053    Keith Hervey
14577  Keith Harrison
16166  Keith Reynolds