### Handling Null Values in the data

In [25]:
import pandas as pd
import numpy as np

In [26]:
toffee = pd.read_csv("././1.Instructors_Tutorial/warmup-data/coffee.csv")
coffee = toffee.copy()

In [27]:
coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [28]:
coffee.loc[0:2, "Units Sold"] = np.nan

In [29]:
coffee.isnull().sum()

Day            0
Coffee Type    0
Units Sold     3
dtype: int64

In [30]:
coffee[coffee["Units Sold"].isnull()]

       Day Coffee Type  Units Sold
0   Monday    Espresso         NaN
1   Monday       Latte         NaN
2  Tuesday    Espresso         NaN

In [31]:
coffee.fillna(coffee["Units Sold"].mean())

          Day Coffee Type  Units Sold
0      Monday    Espresso   35.454545
1      Monday       Latte   35.454545
2     Tuesday    Espresso   35.454545
3     Tuesday       Latte   20.000000
4   Wednesday    Espresso   35.000000
5   Wednesday       Latte   25.000000
6    Thursday    Espresso   40.000000
7    Thursday       Latte   30.000000
8      Friday    Espresso   45.000000
9      Friday       Latte   35.000000
10   Saturday    Espresso   45.000000
11   Saturday       Latte   35.000000
12     Sunday    Espresso   45.000000
13     Sunday       Latte   35.000000

In [32]:
coffee = coffee.dropna()
coffee.isnull().sum()

Day            0
Coffee Type    0
Units Sold     0
dtype: int64

In [33]:
coffee.head()

         Day Coffee Type  Units Sold
3    Tuesday       Latte        20.0
4  Wednesday    Espresso        35.0
5  Wednesday       Latte        25.0
6   Thursday    Espresso        40.0
7   Thursday       Latte        30.0