### Working with JSON/SQL

In [22]:
import pandas as pd

In [23]:
pd.read_json("./Datasets/train.json")

          id      cuisine                                        ingredients
0      10259        greek  [romaine lettuce, black olives, grape tomatoes...
1      25693  southern_us  [plain flour, ground pepper, salt, tomatoes, g...
2      20130     filipino  [eggs, pepper, salt, mayonaise, cooking oil, g...
3      22213       indian                [water, vegetable oil, wheat, salt]
4      13162       indian  [black pepper, shallots, cornflour, cayenne pe...
...      ...          ...                                                ...
39769  29109        irish  [light brown sugar, granulated sugar, butter, ...
39770  11462      italian  [KRAFT Zesty Italian Dressing, purple onion, b...
39771   2238        irish  [eggs, citrus fruit, raisins, sourdough starte...
39772  41882      chinese  [boneless chicken skinless thigh, minced garli...
39773   2362      mexican  [green chile, jalapeno chilies, onions, ground...

[39774 rows x 3 columns]

In [24]:
import mysql.connector

In [25]:
conn = mysql.connector.connect(host= "localhost",user = "root",password = "", database = "world")

In [26]:
df =pd.read_sql_query("SELECT * FROM CITY WHERE CountryCode = 'IND'", conn)

C:\Users\abhi0\AppData\Local\Temp\ipykernel_23548\3587292218.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df =pd.read_sql_query("SELECT * FROM CITY WHERE CountryCode = 'IND'", conn)

In [27]:
df = df.drop(columns="ID",axis=1)
df

                   Name CountryCode        District  Population
0       Mumbai (Bombay)         IND     Maharashtra    10500000
1                 Delhi         IND           Delhi     7206704
2    Calcutta [Kolkata]         IND    West Bengali     4399819
3      Chennai (Madras)         IND      Tamil Nadu     3841396
4             Hyderabad         IND  Andhra Pradesh     2964638
..                  ...         ...             ...         ...
336        Ambala Sadar         IND         Haryana       90712
337          Baidyabati         IND    West Bengali       90601
338               Morvi         IND         Gujarat       90357
339             Raigarh         IND     Chhatisgarh       89166
340            Vejalpur         IND         Gujarat       89053

[341 rows x 4 columns]