In [41]:
import requests
import pandas as pd
import time

In [42]:
API_KEY = "9a61ea76efmsh208df165153f970p1e9330jsn0eaf6e2aae95"
url = 'https://streaming-availability.p.rapidapi.com/shows/search/filters'
headers = {
    'X-RapidAPI-Host': 'streaming-availability.p.rapidapi.com', 
	'X-RapidAPI-Key' : API_KEY
}
params = {
    "country":"us"
}

In [43]:
response = requests.get(url,headers=headers,params=params)
df = response.json()['shows']
df

KeyError: 'shows'

In [ ]:
response.json()

{'shows': [{'itemType': 'show',
   'showType': 'movie',
   'id': '242683',
   'imdbId': 'tt11649634',
   'tmdbId': 'movie/636293',
   'title': 'GANG',
   'overview': "After getting into big trouble, Choi Ji-hoon is transferred to Daehoon High, the worst school in Korea. Ji-hoon's goal is simple: become the top dog of the new school by winning the school's underground fight club.",
   'releaseYear': 2020,
   'originalTitle': '갱',
   'genres': [{'id': 'action', 'name': 'Action'}],
   'directors': ['Jo Ba-reun'],
   'cast': ['Kim Ra Hee',
    'Cha Ji-hyuk',
    'Jo Sun-ki',
    'Ock Yun-jung',
    'Baek Jae-min',
    'Kim Dae-han',
    'Lee Jung-hyun'],
   'rating': 45,
   'runtime': 94,
   'imageSet': {'verticalPoster': {'w240': 'https://cdn.movieofthenight.com/show/242683/poster/vertical/en/240.jpg?Expires=1786426333&Signature=BeNxbohp~QckMFmuUH0bhABWss6ursLsIEpQNaPxJNX5Tt5MKp4J7AH80Dz1Wa0MAl7Kfz8h4VU97678-lyXv9g88KuGFcOo~H4i63x0EF-z~R~b3q8NbSgWScHw~yJKHaj1Fv213D~3AGeS5lGn2CbRzxz9Ilyb0SlVPgAOwZnyDzuFQ3bsfrWdYm873kdOMmelCRweC6ix1rRo9vnjE2pza5KeAA4VLjg3kG93YmBYo5fj7fNacTOAW-xcryxHvXPOjMDaHPw7oKZvWcGyhUvcDXiN-gZfMrE1qUek7YtxpIc1Oq8v9IXDFWpb6MSKonotyXQ8fJZEIjIVNiXOYg__&Key-Pair-Id=KK4HN3OO4AT5R',
     'w360': 'https://cdn.movieofthenight.com/show/242683/poster/vertical/en/360.jpg?Expires=1786426333&Signature=Mj0~eRcxGFe3DN5MV2qHe2LAenCgbT4DK5L7G08~HazTpZVvMr11gjMJFQzmIQ6kp6QOaJNRf~~g4DhdX6rW2~NZFomJsgs1ZElkP~ydTbbJ16fojnGwAheTQRyVvNZvGuHuyF6npQtJPXzAd6PzdjRXGg0-dyq2f4cVDKzfMifmmggtJTN57Na9hMujLX7FjOJBAp1pnodBskeUc4V2Z86ACLBuRIC60xsyNk1Qe4P-9c5Yca698WOjGKZVIU0BHEv-YKTg8hsiDPLotZ9zHAPGOkFzcbxTwI~YCFqpiXSi5La-2x9GEmg3LwFQqpKopTna-MfKLcC8n7T14Pqm-A__&Key-Pair-Id=KK4HN3OO4AT5R',
     'w480': 'https://cdn.movieofthenight.com/show/242683/poster/vertical/en/480.jpg?Expires=1786426333&Signature=IegWkDIvGgJFjv0d53OIRwVQJeXSXa~6x~Ifrk5S8~nMav4k4Q8O~OaK-Ojy0uMJcyXbqPC7lWlPkFnvMoDrsSaWn8oqo0Y79PIPjcc-NONiBntDM4egDJKDsfzbeb1thILXZWDvvC1~~bNP8W4kYes2yL9n-Fpi1-2HteZiYULpsTn7TqQS-Lj0tB55dTF0bNHPfvlRoOXPhgKOMroDfCgLVqVZiU8qQ2toe0Y-GjK-ujojk~J9BmjHKf9griwEez7A4CUkRwIEVJyUA1RsT14R~7ZXlNgSmLwE2AZnrxJfqKV9RePLqV13ISNl-IRi6YrODDjI8v9TXTrVXZ1PWg__&Key-Pair-Id=KK4HN3OO4AT5R',
     'w600': 'https://cdn.movieofthenight.com/show/242683/poster/vertical/en/600.jpg?Expires=1786426333&Signature=INMGrNrwVmyE9SW7yACkdMtYm0Ymtd-yychwRAcPzoRq8DM~eure-XXOOSB~56WwYG6renL2xdlSxTsfvMepYEU44CqcV92sfaGFRTUJFnYXEch6BwdaPq8CY~p4f2MsvRq24oCNoGIF7WVI1yRfv8mool8K~Bp-peziTS7vve54LrB1oQQdKspb99udGh~W9o~2J4xAt62Dk2CLSB4QVixjJbq-fP~GpE-8WbiggaTnnrQkQczRwIFaK1z1Bap0O6IdiY6rql5Sw3OZbEcQ6TTBmRPsC8zEfMT9WBOsEoKwjNipuPnIXC0IQQlQ4PoLLwxf~-oz2QazH7MEeD8gPA__&Key-Pair-Id=KK4HN3OO4AT5R',
     'w720': 'https://cdn.movieofthenight.com/show/242683/poster/vertical/en/720.jpg?Expires=1786426333&Signature=Bo1vwYNFQhLmrJxgGpd9vbsiiVvm8HTb3wcZxG60Oxec43FXaBbn8t1kR8TLYwPXCmXAx-Htcnpis~WpWhc5JpCSRFMYuJThxSp~0Bmx9G12HbgEJmsCKLc6H0vvYLsNt56F061k6ZjcUnP3XbLw9cZH-Ql6NKe1NN~p7VoOSEg4PElZn8wcmtZM7QktX6gQY~6HGq4QWrgPB4Y7DNlWYDw13BDPoe6UslM84YiCSifJ~wm~aOr-kVP79aSiltDw3zBtlX3c1AYJVtc8EZx2-6ERDtkY7AwDQZ8Fd~Iy5v7zDdSGdQOXLoRmUfl9KYmwWi7JEd9BbCd5z9Z8g4mC1Q__&Key-Pair-Id=KK4HN3OO4AT5R'},
    'horizontalPoster': {'w360': 'https://cdn.movieofthenight.com/show/242683/poster/horizontal/en/360.jpg?Expires=1786426335&Signature=hOd2f-NqVp6kpTUfpIvFmsdyJQEHDL~kiopCfOyBH4gjXj0BmzaMy~H3~enqZc4~MTkl7FvDKJun6MsTb9f9T2wyc0r8hxBdOb2gvdjRAJpG~YolE7iq6xeZ06wACctThkOxRansz5FfPQlRdD1Hs5biDhxxMH-AJSGT-wWpzjS0YQ5lN6~zcVGNVvhenNHn11cKx-WI3Ao1rLHi9Ft8f9JNLqQqZW2aVE1~5m0oVtf58gKhTN-8tsq1kzZPqaai2pObO6aqXVjjUQvBWF~yWTvK3OO5rvBtisHjrdtM0oc2xnhoblOxHHA3IEdjv3gmOuzUvY0j0mIGMe6PRI2aMg__&Key-Pair-Id=KK4HN3OO4AT5R',
     'w480': 'https://cdn.movieofthenight.com/show/242683/poster/horizontal/en/480.jpg?Expires=1786426335&Signature=Q3a-PcguUAWx3OoB44iybfdnUqzXD8ojn5kmyaeVDmNZJ~zv9vtODaU1PatUPhw6mNd7QRMoTnKcqZ4gPVktYQB9G8scWezV5JliuH62enCpanxUK7gu5YhbOAmVhbujR39sQLZVletJL-VpphqHRe~bBOsiuvZU1pWZM4IFoB571sXbbCOJiDPebXdKRKHM0JXcqsj2vH-vgXbk7ZpMBNMD6h25CxVSuohkXRPelxotYVUNtBPYwdA75KgeVD4BHV7Es8yOAPhya0T8dfQ4wPDQMCPVD61A-Rdbr8mCbK8Ua0HWLA4oxmaQs~ijXGTI3J1jBLif7NhVF1UiXrTltA__&Key-Pair-Id=KK4HN3OO4AT5R',
     'w720': 'https://cdn.movieofthenight.com/show/242683/poster/horizontal/en/720.jpg?Expires=1786426335&Signature=f4WZ2JQd70dhkV67mxWeCEH95jfqCNB7eEsUFQ1ruY3nG6kIpLV-G5s5Sz-EMBfCVMEsAWuCaJFwVLueBuQHHHG6J8KGm~CuumpP-if~Nhbf1FkxlQQ4fTFI6qFE~OhiBWVmFiGFQyR051XI4Mz4LkU50AgfaBMJ6U8Rd2PVIyD0IrlcXtL76v2wgK7kpzttlLogEoWjOjhTOq-qPBntyDidn377v13lUDCR59ixvkjpwE1paHLChD59nCl8OTWGEpr59yUhDF2w7rr6X4K6Q4eW1FOuB-pq~4lJa8RJx0hWsVP5WvGo9MUtLp2Br~VZWgMHYDfvvmHg56zNpyptyA__&Key-Pair-Id=KK4HN3OO4AT5R',
     'w1080': 'https://cdn.movieofthenight.com/show/242683/poster/horizontal/en/1080.jpg?Expires=1786426335&Signature=hVUv-p7RO2UY4kKf2--UIKYRH2JdhuZCLQncmS4-sVaxq~AU8Tvv5i~j0xFmtx7QbyIqY8kzD-1R000hcLFzB6aTaU2NuWvEDXFAuk57IAEaT04ITGEViY2U3adDOZmGqju3drP~q9bTym79VNfla-sfZol43XLgsgYAbE-JlL8yt5E-bbLl2vZbWHjprcZUGOcljFcOnx4NqFe977yNDDkgPibMKstoz92sNVDe00P6kDDDtv4C87NoVZQ736OR7-zUQDxlk6lT8Y~CPA7QSNrECN3naQhwuLK1bY3ioXXT6EVO4D1nOVnBs1EZ-YoptnLAou8NY2rb6zXA9-~6QQ__&Key-Pair-Id=KK4HN3OO4AT5R',
     'w1440': 'https://cdn.movieofthenight.com/show/242683/poster/horizontal/en/1440.jpg?Expires=1786426335&Signature=c12E16yp~7elQDI9k0Gpv8WKbsFNj4djyx4rilxp1E8XfnRa4d7SxLPxXkbFMqslbJZV5kId8bp79QxjHDYlp-UWY72IJsCyDaLE1ApQQJflIB-kKW3WbBGPcot21Q6XXO80QTxVOWjDK-zhFl5ZikHvBq4vxTsZEMx7TkC2J-d4pMXRNU2ma8E6pqHIV80hutmTsTj1himaHZA-Bjc48SHop8mQXgDla4LBCUDYaTYBl5xkiroh54dT3lI9qwsr6ZjMOe8iyH5QyAetTeuEylL0fckgqq50VT~SLlQteeJa6IJDDoNYP3BRvR7NJpv1WirWPPLck6DIpUUCf9JNSA__&Key-Pair-Id=KK4HN3OO4AT5R'},
    'horizontalBackdrop': {'w360': 'https://cdn.movieofthenight.com/show/242683/backdrop/horizontal/360.jpg?Expires=1786426331&Signature=F9jOj2eP20PkNWFmv6A2cHWfBnwF2KFrbrqahy~87GF29Mb0BjbjVL2NxzvpQ5yVm7NKNrfIQbYL-j-B~odgRv34dg7W~iWknMf1XeMtbze8YyySYZzMx5zMqa15eBuO7UOo2Z34kDAj85V9vzHN8tBVujN69VA6Zc-A2GsWpGI9v1XWHN7jQ2gKaMjjLoy~I6HJGkcpXf1ou67ERaFgyVzs9DrlbgtsQPfnKsZtMRr5tsqjV~sEQYvXU5mCaN0T4yhGE6K4j9LccJ5SlcCc8rLnneFS-XrZu2Gryb-dLPkS1gcfCgbNyYSlPOLJDReXEa5tffwsdAEKOI9To8bYWA__&Key-Pair-Id=KK4HN3OO4AT5R',
     'w480': 'https://cdn.movieofthenight.com/show/242683/backdrop/horizontal/480.jpg?Expires=1786426331&Signature=iloUfnH-7K3qYwG9eKV2iXRyRJWdVSQFGlx2IjhetZiR2vnCaPU-QKggfzAsApGG5f2PaYGmGgffL87rlXRlH75g0d5SJERpD17dkcy-S~QpSB9ARFsVtoWri0TJrK2uV3cSgQmaeJQayNCnjZiI8zSSywiiEgEkBU4UA8AJZjhFL8uPkpyo~UizIIx2fcKb5Y-73mj~183YiJBm~BOeAFUYWJrYNN3HnLgBRxCtLFHrT2YyAOZn7fxWaiYZfA3nDttRTh41tlGx5yy6q5ZobNqelIQSqduLFBku50TlDYQ7SCWJb9SKn40sF8ybVOlZTkFHKOe6PiMO2U8ANJMzjg__&Key-Pair-Id=KK4HN3OO4AT5R',
     'w720': 'https://cdn.movieofthenight.com/show/242683/backdrop/horizontal/720.jpg?Expires=1786426331&Signature=JWlf-L2RGDmnKIYc-jqA-T1L5fPsXz9IpFo~0ureDImmz1pGWcUN288JN9aZG4JxbzM0WFuoprEkx3-vPjljsQW1Pcd~M7WKlovIoOIYNltz2cAeECsSYSxNGFeYxeU75Plct~UC3DJHvq2qYyM7NydfbyOXSr-hTC0T6D0SroSVCZy8Q5NBJESB-nvm2S~sYwMEJj02hwLUEdQDyS1zPZJwLiYUYjA02pI5hq9FBUDZ3fZneUXSAUmu8MspPRxKFFTky4YewaApqhuA3VStL49tb5Y3lo5ktoXCIMxolw7iLHmZo1DvJzUUEhiACI9bJTprn9NAgsXpYLP9J7a6pA__&Key-Pair-Id=KK4HN3OO4AT5R',
     'w1080': 'https://cdn.movieofthenight.com/show/242683/backdrop/horizontal/1080.jpg?Expires=1786426331&Signature=Lm-~YX~mW4nok9~~aFvLnb6NI-yG6uwGHFAlH30usfTmbxwitzpHyEMzdbqWI8NZt4j-c5n0QiG7jnt6CmvMvwmLfgOaVtrpS-5d9GIy-kacfPxhOrfmjGpOYL1fwKjACXBw8L4KNjmKgXey16wMdrLpnAMPcD9JJdXvLHPjII8z--9Lnt-~gJHr0gVXkNbHjqOteFg2kaNSctLQfBGOmd~fvt2XQ5BMPkGgDrHW7m3isQDUlrD6LwqqVS742J9DgJYDPvJJTInWRGhxxEH1AN4syL~EtQJ8znspvkiMP6DjwHuat9YBqcdFHkS5w-YLAmX9P-lW5THxeVMY~3MWDQ__&Key-Pair-Id=KK4HN3OO4AT5R',
     'w1440': 'https://cdn.movieofthenight.com/show/242683/backdrop/horizontal/1440.jpg?Expires=1786426331&Signature=GmEcLCntKfFU3K3X3mDDKycdR8I9r63HEXgDXryA4wgGZHbgKDjhfMZgGo6nbvJ~y3Q759uFiLclDoHA8ndpZB9KkcwHFu0VrDm7-iCPhET9WBVh2-vDkrlamitC50Z1WFWW5IEcbguVKyWV~l7SdEBszbv8wexoiUG8v5BKKvZMEIs3btiAnGHHD8TZjWQvYtGDEHnN-aMuOktScU546WEQ7zgcJ~oGdk49pJmoc5xtt4vhdFIw7T4azZJl7oyy2kCfsGEslchhNCSsKTj5Hrhm7tnj199Z2uX6uEQ3f4Ja7l91c9Md6Y8NhMHGPo7mEbQU~AObG1Xtf083N2ZQnw__&Key-Pair-Id=KK4HN3OO4AT5R'}},
   'streamingOptions': {'us': [{'service': {'id': 'prime',
       'name': 'Prime Video',
       'homePage': 'https://www.amazon.com/gp/video/storefront/',
       'themeColorCode': '#00A8E1',
       'imageSet': {'lightThemeImage': 'https://media.movieofthenight.com/services/prime/logo-light-theme.svg',
        'darkThemeImage': 'https://media.movieofthenight.com/services/prime/logo-dark-theme.svg',
        'whiteImage': 'https://media.movieofthenight.com/services/prime/logo-white.svg'}},
      'type': 'subscription',
      'link': 'https://www.amazon.com/gp/video/detail/B095MV2GJM/ref=atv_dp',
      'quality': 'sd',
      'audios': [{'language': 'kor'}],
      'subtitles': [{'closedCaptions': True, 'locale': {'language': 'eng'}}],
      'expiresSoon': False,
      'availableSince': 1690092666},
     {'service': {'id': 'prime',
       'name': 'Prime Video',
       'homePage': 'https://www.amazon.com/gp/video/storefront/',
       'themeColorCode': '#00A8E1',
       'imageSet': {'lightThemeImage': 'https://media.movieofthenight.com/services/prime/logo-light-theme.svg',
        'darkThemeImage': 'https://media.movieofthenight.com/services/prime/logo-dark-theme.svg',
        'whiteImage': 'https://media.movieofthenight.com/services/prime/logo-white.svg'}},
      'type': 'buy',
      'link': 'https://www.amazon.com/gp/video/detail/B095MV2GJM/ref=atv_dp',
      'quality': 'sd',
      'audios': [{'language': 'kor'}],
      'subtitles': [{'closedCaptions': True, 'locale': {'language': 'eng'}}],
      'price': {'amount': '7.99', 'currency': 'USD', 'formatted': '7.99 USD'},
      'expiresSoon': False,
      'availableSince': 1690092666},
     {'service': {'id': 'prime',
       'name': 'Prime Video',
       'homePage': 'https://www.amazon.com/gp/video/storefront/',
       'themeColorCode': '#00A8E1',
       'imageSet': {'lightThemeImage': 'https://media.movieofthenight.com/services/prime/logo-light-theme.svg',
        'darkThemeImage': 'https://media.movieofthenight.com/services/prime/logo-dark-theme.svg',
        'whiteImage': 'https://media.movieofthenight.com/services/prime/logo-white.svg'}},
      'type': 'buy',
      'link': 'https://www.amazon.com/gp/video/detail/B095MV2GJM/ref=atv_dp',
      'quality': 'hd',
      'audios': [{'language': 'kor'}],
      'subtitles': [{'closedCaptions': True, 'locale': {'language': 'eng'}}],
      'price': {'amount': '9.99', 'currency': 'USD', 'formatted': '9.99 USD'},
      'expiresSoon': False,
      'availableSince': 1690092666},
     {'service': {'id': 'prime',
       'name': 'Prime Video',
       'homePage': 'https://www.amazon.com/gp/video/storefront/',
       'themeColorCode': '#00A8E1',
       'imageSet': {'lightThemeImage': 'https://media.movieofthenight.com/services/prime/logo-light-theme.svg',
        'darkThemeImage': 'https://media.movieofthenight.com/services/prime/logo-dark-theme.svg',
        'whiteImage': 'https://media.movieofthenight.com/services/prime/logo-white.svg'}},
      'type': 'rent',
      'link': 'https://www.amazon.com/gp/video/detail/B095MV2GJM/ref=atv_dp',
      'quality': 'hd',
      'audios': [{'language': 'kor'}],
      'subtitles': [{'closedCaptions': True, 'locale': {'language': 'eng'}}],
      'price': {'amount': '2.99', 'currency': 'USD', 'formatted': '2.99 USD'},
      'expiresSoon': False,
      'availableSince': 1690092666},
     {'service': {'id': 'prime',
       'name': 'Prime Video',
       'homePage': 'https://www.amazon.com/gp/video/storefront/',
       'themeColorCode': '#00A8E1',
       'imageSet': {'lightThemeImage': 'https://media.movieofthenight.com/services/prime/logo-light-theme.svg',
        'darkThemeImage': 'https://media.movieofthenight.com/services/prime/logo-dark-theme.svg',
        'whiteImage': 'https://media.movieofthenight.com/services/prime/logo-white.svg'}},
      'type': 'rent',
      'link': 'https://www.amazon.com/gp/video/detail/B095MV2GJM/ref=atv_dp',
      'quality': 'sd',
      'audios': [{'language': 'kor'}],
      'subtitles': [{'closedCaptions': True, 'locale': {'language': 'eng'}}],
      'price': {'amount': '1.99', 'currency': 'USD', 'formatted': '1.99 USD'},
      'expiresSoon': False,
      'availableSince': 1690092666}]}},
  {'itemType': 'show',
   'showType': 'movie',
   'id': '170557',
   'imdbId': 'tt1519633',
   'tmdbId': 'movie/113649',
   'title': 'Be with Me',
   'overview': "Three intertwined tales reveal eerie depths: a devoted shopkeeper, teenage soulmates, and a timid guard face love's haunting shadows.",
   'releaseYear': 2010,
   'originalTitle': '귀',
   'genres': [{'id': 'horror', 'name': 'Horror'},
    {'id': 'romance', 'name': 'Romance'}],
   'directors': ['Kim Jho Gwang-soo',
    'Yeo Myeong-jun',
    'Jo Eun-kyung',
    'Hong Dong-myung'],
   'cast': ['Han Yeri',
    'Hong Jong-hyun',
    'Hwang Byeong-gug',
    'Shin Ji-soo',
    'Kim Kkob-bi',
    'Lee Chae-eun',
    'Lee Jong-suk'],
   'rating': 54,
   'runtime': 108,
   'imageSet': {'verticalPoster': {'w240': 'https://cdn.movieofthenight.com/show/170557/poster/vertical/en/240.jpg?Expires=1786883833&Signature=LiFWP6jEN0K1OtaeGDc1cXNj31ViI-M2DGG0p6I80jkvP3osx3-4EyGEfQ7T1i7W5wx0Qpzy3UzfvWA5QOciqzLQXCpyMWHp4llv28dQbBhZtBnwWN5HJP9U1l5u2E-bMNeB4GEDrtSXUeRME3cfJ2xTskz13YikCVr97NQg3hAsdVQPBbWrUAcJ2NvR8AVcnn30tzz~zoS0-scFC~OSd~qW7IF7rjKMomZDIuWLzGMlZSlFq5LYNq1A7oltlMBeZ0ubZHgW8~riAW3Km726JLkUEWBn0QVWmfBylvwu8TkXyhJuAIdj5ziIWlvHTm5qVSy8FPsmr1aYSkUi5xo2Ig__&Key-Pair-Id=KK4HN3OO4AT5R',
     'w360': 'https://cdn.movieofthenight.com/show/170557/poster/vertical/en/360.jpg?Expires=1786883833&Signature=AXbAMjUtbRjBoHPef1InmZasCnDbyUwyVvt7VD1ao7ZzjugY6hMhwAdq0aVGZ7E9Nw6dTYoX8E9k7CFK-8jVZMlMqfVPTdTaTQPSqpXZ5kYD9gnHJ3N74KEoFMW7OKzBC68e~M8HftrPxcP-fgcMdKP~Tsp52fIyyceuNPSoXG6756uJGonboregkZd6WkDqHGB506~WI~CfZ8T5hb4Hc6zPTDkc9VdtFb0a3SDdg1UvKRWLSNemJKslRX4hLl66GLTXwPKDAZ3V2n6CqxeIKmC7CwGxI6zrJrA7BwIRs00thQ-Y7bBVnTIXmMdXMDndSb5DQqRJev7KJRsH6p6nhw__&Key-Pair-Id=KK4HN3OO4AT5R',
     'w480': 'https://cdn.movieofthenight.com/show/170557/poster/vertical/en/480.jpg?Expires=1786883833&Signature=BRy7FzKSsxYr-CrDTovqXz9gCfGecUBL0BmI--qIdTVyFwrCdyg7q3fv493~RmKBa2TwLeXSoSj9dgAQBDTsmmziCP71SPIyDUEo4yK0pYpZ1leDP5nJDaNSYfPBU9QHK-bB17W8xsTwhvIpGbGI4vzM2JFdpywPeTUQDGxXYGiIDoTNvFW5KamRH6Ydop-ZI-vJJ9SYdz03vjxTh0Y18ozNVLPEmVEZcIRCVL88El8RY73-M2z4S3b6YiBM9vNrm5QJlGtVPxukjkdvBjozM7TdjYAqK0keKR1W9DXeemc8quhKOrh7wIk83oLKWdEj44H42FOawi-v8FvQXU21kw__&Key-Pair-Id=KK4HN3OO4AT5R',
     'w600': 'https://cdn.movieofthenight.com/show/170557/poster/vertical/en/600.jpg?Expires=1786883833&Signature=ltaHaU2RgR~kNol8MBOIdh20ioA6MsZNlNPnp2GEclpWp1HNpvsgFV5KHigkIwtXnJmi0vNDb4AVjwgSiEoGRmaCnBzepDK~pNPjbzo8TowA6ZNLwaOQ5xk8Yxkw1IlJIMW9P9AqzMSNqE~W21CVwHZjn433znMdnE3sXECFQwKufh1cb1Qxe7XNslyAuxXkd5kVT5EjuBdLo9j1D3Ql8ZTl2w4yYpKR4Ws-sRv-BWSiRUhtHv~XOZcBB1VElyqI-ziTirf-aDUgEZnMSsPhJTgXVbiJgf3LDXXHONUrVtOgbPOIwWyV55puUcl2C33oOEUQv-jI-lJlO64W3K1iYg__&Key-Pair-Id=KK4HN3OO4AT5R',
     'w720': 'https://cdn.movieofthenight.com/show/170557/poster/vertical/en/720.jpg?Expires=1786883833&Signature=c~k8M~DOWTt0g2cvuYTblCRjs9MVIOA1DNiecxaMW3SrUDct0c1-x6nRSsaCG-spXEor3F2jQPLtpME2CfT3ulEhTwxD8hAAWHdnovz1joCKK1Ad~uUE6N6dNCklNgSdx~NNWxrD7nRxNZ~NCZTd52QfGh1Ik7qo4Y-AwF9Z3f8Y9xhXrhWo4uyKYd3IUUK5MiZOIsa~CgRHAyLRqM5z8sWDrIgbge2XU~u1qOk04eqBXF-jM~~qkzDdabGClq4ZOqvhso5pyDfZDS0UNgXNsnwGzMyQmkOlCtpaJA9sEDeFcZIg43eYGhhgZswChCzueHD~4T~OZMtWsWISH~n48w__&Key-Pair-Id=KK4HN3OO4AT5R'},
    'horizontalPoster': {'w360': 'https://www.movieofthenight.com/media/image.svg?title=Be+with+Me&width=360&direction=horizontal',
     'w480': 'https://www.movieofthenight.com/media/image.svg?title=Be+with+Me&width=480&direction=horizontal',
     'w720': 'https://www.movieofthenight.com/media/image.svg?title=Be+with+Me&width=720&direction=horizontal',
     'w1080': 'https://www.movieofthenight.com/media/image.svg?title=Be+with+Me&width=1080&direction=horizontal',
     'w1440': 'https://www.movieofthenight.com/media/image.svg?title=Be+with+Me&width=1440&direction=horizontal'},
    'horizontalBackdrop': {'w360': 'https://cdn.movieofthenight.com/show/170557/backdrop/horizontal/360.jpg?Expires=1786883832&Signature=hh~hVxZGU09X3GG5QvziuZ7YwnXQfT2O4yjslSdTV82x-09Z43u0jRiFzOoSv2VZ~tKa6JiEmBmUgnXC8cwtM5XmgCQ18iEsvQtyUh6HR0N~w0gALdocKFsfq3lcuBpF5LmsYXPI6rJkiKQmxr3cDhMFJruzE3cVI~ZpntU4xJ9wx2uzro3eagkgjqU7zRdv7modOMHHyfUIHEF1wwAHcYJwnD6axkE0-LeNiMWyohrdzGTXgf4Jin14CviAY7QWwrV1fFr6LtoUQShu1EiCT4YiJ~h4-VSNzq-rG6qj8Lkkb9VOLTUrEIGcsw3p1vZR7zyYy4o-LZS2wIctDQ6yBw__&Key-Pair-Id=KK4HN3OO4AT5R',
     'w480': 'https://cdn.movieofthenight.com/show/170557/backdrop/horizontal/480.jpg?Expires=1786883832&Signature=G8OatohFcQWQGzc~L6Kf~tPEA9UieEgLwaKHIOtR~tWtuI69MEqKE3J2P0dE8KbkVSjIuepypTmWcmsWmMJGzSCezDWm3wb2VZk7CRdppRnAo5oJ4RFUEpN4nCRcDXTzbw6yPsRr0Au9VGiJweMpB8zt1jz9AVSMa27xsK-McIJJyng-rfvp3UWvl0uj5p9~3aNMAilzEZUtl0g7Igl4KYTdKi0bAoOcb7lfRn4LVbnRr76gbZUZapyVwl21icuedrDTjEDDJRRMQ9b7JGzaMhT3QRdXb3MgIdGPxhvFuvpup8B4HIg9lvUsvME5qGsPVdIKdOfWFZ0LS3jD-1cjBw__&Key-Pair-Id=KK4HN3OO4AT5R',
     'w720': 'https://cdn.movieofthenight.com/show/170557/backdrop/horizontal/720.jpg?Expires=1786883832&Signature=F60-Cbkjun0iWSsoJKyoY41sFAR8vdVzymKNtplXJioORd8y0EZQ-39qgc9EcIM~f6FS511KUCfhjWS~j7RN3KcJ-xEW8ftAKeEDew0fAthm--L2bHQlPxE24pNFTgMltHzdTFp3HqTN4m2CXqEpROf2l1n~HI6unC45EkmH1CLXbDFgZUiJ0zcf0fxoo-ZRpIwIb-~IqoYQwUv53hFtEDn1xWJi3J7eqpYUgVvvdFdy0mxCGDNCN2f64O3hzA4iruTU4KJA~7BWUKMtBhcIEDMRuX4oZkFW3rxdwpden~pvTBMDspRM~lcyCclRVnP-Qp-gvL0Vt9OCfvc5i9pW3A__&Key-Pair-Id=KK4HN3OO4AT5R',
     'w1080': 'https://cdn.movieofthenight.com/show/170557/backdrop/horizontal/1080.jpg?Expires=1786883832&Signature=BZFOOuvzzpgpgfzzE2J-tU4tcqljoO-NaNSqBX-Rn1aCN59jZFkm3N7I5MmLTFE-isvdkuuMJywZC9oEuVr60-qvVyOgQvw8rEgFVBSWsSBOA7labGl1jgo1TeFFOZZHr0MGYkfmiwh4UZcB5cJ6jjq9vfMu0YlzCMY6AClCYUkHJYT9kxpaJTZkRtOtvRE8jzrkXivSgHxAeT6jyHNDn1lnh6N0BQsb9leSuiQ73H39cfB1STqPN4Vyli8c44IjlAfemHDsTgLh9cQDVvF5BMqRFmIJDSKDeEv0C9WHJZ2ME~C4wdPqHcr1q-Vs4MdujJvs7mv66H1ws7Y4KxxGfw__&Key-Pair-Id=KK4HN3OO4AT5R',
     'w1440': 'https://cdn.movieofthenight.com/show/170557/backdrop/horizontal/1440.jpg?Expires=1786883832&Signature=ejBxnbuxGoNJfzbBiOplZB3jpAFs15XFDc5H6O1-kzOSjhZfypXwHugFWhajcJWVhPAUGkPCx4R2V3yDc3IhEwGgRnUTPhGfTF~u5Vn2V02h1IsFYXKFZ0I2~p1BtdhyDPK9~Z3I2Syje~utBNsyKdy24vAR8VnELfbD~Bsr-17T4uWRsIWZ-JbnpAqawnVbE2tL6mCcbuWO952Sv4xaR2YvHMMCD6AXOET-zgvUf-FhhEyZyBs5fAfhvAVkAIK5xhJgaqA8EgIRXNaVIgeaz4C-aw-aQKIUDWqk5PYa7jhDfHPCJbVaNWrUaUGRupEJ1IPR-vjbQiv~qwZnVzDCxw__&Key-Pair-Id=KK4HN3OO4AT5R'}},
   'streamingOptions': {'us': [{'service': {'id': 'tubi',
       'name': 'Tubi',
       'homePage': 'https://tubitv.com/',
       'themeColorCode': '#ffff13',
       'imageSet': {'lightThemeImage': 'https://media.movieofthenight.com/services/tubi/logo-light-theme.svg',
        'darkThemeImage': 'https://media.movieofthenight.com/services/tubi/logo-dark-theme.svg',
        'whiteImage': 'https://media.movieofthenight.com/services/tubi/logo-white.svg'}},
      'type': 'free',
      'link': 'https://tubitv.com/movies/12406/be-with-me',
      'quality': 'sd',
      'audios': [],
      'subtitles': [],
      'expiresSoon': False,
      'availableSince': 1716081864}]}},
  {'itemType': 'show',
   'showType': 'movie',
   'id': '57335',
   'imdbId': 'tt7243686',
   'tmdbId': 'movie/478187',
   'title': 'The Swindlers',
   'overview': 'In this crime thriller, a group of unlikely allies have to work together to achieve a common goal: taking down the world’s most legendary con man.',
   'releaseYear': 2017,
   'originalTitle': '꾼',
   'genres': [{'id': 'action', 'name': 'Action'},
    {'id': 'crime', 'name': 'Crime'}],
   'directors': ['Jang Chang-won'],
   'cast': ['Hyun Bin',
    'Yoo Ji-tae',
    'Bae Sung-woo',
    'Park Sung-woong',
    'Nana',
    'Ahn Se-ha',
    'Choi Deok-moon'],
   'rating': 61,
   'runtime': 117,

In [ ]:
params = {
    "country":"us",
    "cursor": "1016:킹덤"
}
response = requests.get(url,headers=headers,params=params)
df1 = pd.DataFrame(response.json()['shows'])[['id','title','releaseYear','overview']]

In [ ]:
df.head()

,id,title,releaseYear,overview
0,242683,GANG,2020.0,"After getting into big trouble, Choi Ji-hoon i..."
1,170557,Be with Me,2010.0,Three intertwined tales reveal eerie depths: a...
2,57335,The Swindlers,2017.0,"In this crime thriller, a group of unlikely al..."
3,15455,Big,NaN,Yun Jae and Gyeong Jun’s souls switch. How wil...
4,17743,The Isle,2000.0,A woman who sells supplies and solace to fishe...

In [47]:
url = "https://streaming-availability.p.rapidapi.com/shows/search/filters"
API_KEY = "9a61ea76efmsh208df165153f970p1e9330jsn0eaf6e2aae95"
headers = {
    'x-rapidapi-key': 'c9202548acmsh2abf92278818bf2p1a9d91jsnc274535793a1',
	'x-rapidapi-host': 'streaming-availability.p.rapidapi.com' 
}

In [49]:
all_rows = []
len = 0

cursor = None

while(True):

    len +=1
    print(len)

    if len == 900:
        break;

    params = {
        "country": "IN"
    }

    if cursor:
        params["cursor"] = cursor

    response = requests.get(url,headers=headers,params=params)
    data = response.json()
    
    page_df = pd.DataFrame(data["shows"])
    page_df= page_df[page_df['showType']=='movie']
    page_df["year"] = page_df.get("releaseYear") 
    page_df = page_df[['id','title','year','overview']]
    

    all_rows.append(page_df)

    if data.get("hasMore") == False:
        break

    cursor = data.get("nextCursor")
    
    time.sleep(0.5)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277
278
279
280
281
282
283
284
285
286
287
288
289
290
291
292
293
294
295
296
297
298
299
300
301
302
303
304
305
306
307
308
309
310
311
312
313
314
315
316
317
318
319
320
321
322
323
324
325
326
327
328
329
330
331
332
333
334
335
336
337
338
339
340
341
342
343
344
345
346
347
348
349
350
351
352
353
354
355
356
357
358
359
360
361
362
363
364
365
366
367
368
369
370
371
372
373
374
375
376
377
378
379
380
381
382
383
384
385
386
387
388
389
390
391
392
393
394
395
396
397
398
399
400
401
402
403
404
405
406
407
408
409
410
411
412
413
414
415
416
417
418
419
420
421
422
423
424
425
426
427
428
429
430
431
432
433
434
435
436
437
438
439
440
441
442
443
444
445
446
447
448
449
450
451
452
453
454
455
456
457
458
459
460
461
462
463
464
465
466
467
468
469
470
471
472
473
474
475
476
477
478
479
480
481
482
483
484
485
486
487
488
489
490
491
492
493
494
495
496
497
498
499
500
501
502
503
504
505
506
507
508
509
510
511
512
513
514
515
516
517
518
519
520
521
522
523
524
525
526
527
528
529
530
531
532
533
534
535
536
537
538
539
540
541
542
543
544
545
546
547
548
549
550
551
552
553
554
555
556
557
558
559
560
561
562
563
564
565
566
567
568
569
570
571
572
573
574
575
576
577
578
579
580
581
582
583
584
585
586
587
588
589
590
591
592
593
594
595
596
597
598
599
600
601
602
603
604
605
606
607
608
609
610
611
612
613
614
615
616
617
618
619
620
621
622
623
624
625
626
627
628
629
630
631
632
633
634
635
636
637
638
639
640
641
642
643
644
645
646
647
648
649
650
651
652
653
654
655
656
657
658
659
660
661
662
663
664
665
666
667
668
669
670
671
672
673
674
675
676
677
678
679
680
681
682
683
684
685
686
687
688
689
690
691
692
693
694
695
696
697
698
699
700
701
702
703
704
705
706
707
708
709
710
711
712
713
714
715
716
717
718
719
720
721
722
723
724
725
726
727
728
729
730
731
732
733
734
735
736
737
738
739
740
741
742
743
744
745
746
747
748
749
750
751
752
753
754
755
756
757
758
759
760
761
762
763
764
765
766
767
768
769
770
771
772
773
774
775
776
777
778
779
780
781
782
783
784
785
786
787
788
789
790
791
792
793
794
795
796
797
798
799
800
801
802
803
804
805
806
807
808
809
810
811
812
813
814
815
816
817
818
819
820
821
822
823
824
825
826
827
828
829
830
831
832
833
834
835
836
837
838
839
840
841
842
843
844
845
846
847
848
849
850
851
852
853
854
855
856
857
858
859
860
861
862
863
864
865
866
867
868
869
870
871
872
873
874
875
876
877
878
879
880
881
882
883
884
885
886
887
888
889
890
891
892
893
894
895
896
897
898
899
900

In [ ]:
df = pd.concat(all_rows,ignore_index=True)
df.head()

C:\Users\abhi0\AppData\Local\Temp\ipykernel_23732\1284512278.py:1: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(all_rows,ignore_index=True)

,id,title,year,overview
0,351292,The Hand,2023.0,"A man and his wife, encounter a grotesque look..."
1,2700384,Sleep,2023.0,How well do you really know the person sleepin...
2,10253,The Call,2020.0,Connected by phone in the same home but 20 yea...
3,6176,The Wailing,2016.0,A policeman races against time to save his dau...
4,40092,Confidential Assignment,2017.0,North Korean detective Lim Cheol-ryung (Hyun B...

In [53]:
df.to_csv('movies.csv')

In [54]:
df

,id,title,year,overview
0,351292,The Hand,2023.0,"A man and his wife, encounter a grotesque look..."
1,2700384,Sleep,2023.0,How well do you really know the person sleepin...
2,10253,The Call,2020.0,Connected by phone in the same home but 20 yea...
3,6176,The Wailing,2016.0,A policeman races against time to save his dau...
4,40092,Confidential Assignment,2017.0,North Korean detective Lim Cheol-ryung (Hyun B...
...,...,...,...,...
13649,40924,The Charge of the Light Brigade,1968.0,The contrasts between Victorian England’s aris...
13650,205597,The Chauffeur,2012.0,
13651,33231,The Cheap Detective,1978.0,"Set in 1940, a parody of Humphrey Bogart's hit..."
13652,5458624,The Cheating Game,2023.0,After her cheating boyfriend's sex tape goes v...
13653,242285,The Chef,2019.0,"In the near future, when all labor works are r..."

In [56]:
df.shape

(13654, 4)