## Encoding

### Categorical Data is divided into two types - nominal(no comparision) and ordinal(has a order)  
### When our input cols have a Categorical Data(Ordinal) we do ordinal encoding
### When our input cols have a Nominal Categorical Data we do One-Hot Encoding
### When our output col have a Categorical Data(ordinal) we do label encoding

In [42]:
import pandas as pd

In [43]:
df = pd.read_csv('./Dataset/Customer.csv')

In [44]:
df.head()

   age  gender   review education purchased
0   30  Female  Average    School        No
1   68  Female     Poor        UG        No
2   70  Female     Good        PG        No
3   72  Female     Good        PG        No
4   16  Female  Average        UG        No

In [45]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(df.iloc[:,2:-1],df.iloc[:, -1],random_state=42, test_size= 0.2)
x_train.shape, x_test.shape

((40, 2), (10, 2))

In [46]:
x_train.head()

     review education
12     Poor    School
4   Average        UG
37  Average        PG
8   Average        UG
3      Good        PG

In [47]:
from sklearn.preprocessing import OrdinalEncoder

ode = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])
ode.fit(x_train)

x_train = ode.transform(x_train)
x_test = ode.transform(x_test)

In [48]:
ode.categories

[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']]

In [49]:
x_train = pd.DataFrame(x_train, columns=[['review','education']])
x_train.head()

  review education
0    0.0       0.0
1    1.0       1.0
2    1.0       2.0
3    1.0       1.0
4    2.0       2.0

In [50]:
y_train.head()

12     No
4      No
37    Yes
8      No
3      No
Name: purchased, dtype: object

In [51]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
le.fit(y_train)

y_train = le.transform(y_train)
y_test = le.transform(y_test)

In [52]:
y_train

array([0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0])